"""
Integration tests for summary workflow.

Tests summary generation including sync/async modes,
audience targeting, and LLM provider integration.
"""
import pytest
from unittest.mock import patch, MagicMock


class TestSummarySyncWorkflow:
    """Test synchronous summary generation workflow."""

    def test_generate_summary_for_patient_with_notes(self, seeded_database):
        """Test generating summary for patient with existing notes."""
        client = seeded_database["client"]
        patient = seeded_database["patients"][0]  # Has notes

        with patch("app.services.summary_service.get_llm_provider") as mock_provider:
            mock_llm = MagicMock()
            mock_llm.generate_summary.return_value = "Patient summary generated by LLM"
            mock_provider.return_value = mock_llm

            response = client.get(
                f"/api/v1/patients/{patient.id}/summary?audience=clinician&max_length=500"
            )

            assert response.status_code == 200
            data = response.json()
            assert "heading" in data
            assert data["heading"]["name"] == patient.name
            assert "age" in data["heading"]
            assert "mrn" in data["heading"]
            assert "summary" in data
            assert data["note_count"] == 2

    def test_generate_summary_clinician_audience(self, seeded_database):
        """Test summary generation for clinician audience."""
        client = seeded_database["client"]
        patient = seeded_database["patients"][0]

        with patch("app.services.summary_service.get_llm_provider") as mock_provider:
            mock_llm = MagicMock()
            mock_llm.generate_summary.return_value = "Clinical summary with medical terminology"
            mock_provider.return_value = mock_llm

            response = client.get(
                f"/api/v1/patients/{patient.id}/summary?audience=clinician"
            )

            assert response.status_code == 200
            mock_llm.generate_summary.assert_called_once()
            call_args = mock_llm.generate_summary.call_args
            assert call_args[1]["audience"] == "clinician" or call_args[0][2] == "clinician"

    def test_generate_summary_family_audience(self, seeded_database):
        """Test summary generation for family audience."""
        client = seeded_database["client"]
        patient = seeded_database["patients"][0]

        with patch("app.services.summary_service.get_llm_provider") as mock_provider:
            mock_llm = MagicMock()
            mock_llm.generate_summary.return_value = "Family-friendly summary"
            mock_provider.return_value = mock_llm

            response = client.get(
                f"/api/v1/patients/{patient.id}/summary?audience=family"
            )

            assert response.status_code == 200

    def test_generate_summary_custom_max_length(self, seeded_database):
        """Test summary generation with custom max length."""
        client = seeded_database["client"]
        patient = seeded_database["patients"][0]

        with patch("app.services.summary_service.get_llm_provider") as mock_provider:
            mock_llm = MagicMock()
            mock_llm.generate_summary.return_value = "Short summary"
            mock_provider.return_value = mock_llm

            response = client.get(
                f"/api/v1/patients/{patient.id}/summary?max_length=200"
            )

            assert response.status_code == 200

    def test_summary_for_nonexistent_patient(self, client):
        """Test summary generation for patient that doesn't exist."""
        response = client.get("/api/v1/patients/99999/summary")
        assert response.status_code == 404
        assert response.json()["detail"] == "Patient not found"

    def test_summary_for_patient_without_notes(self, client):
        """Test summary generation for patient with no notes."""
        # Create patient without notes
        patient = client.post("/api/v1/patients", json={
            "name": "No Notes Patient",
            "date_of_birth": "1990-01-01"
        }).json()

        with patch("app.services.summary_service.get_llm_provider") as mock_provider:
            mock_llm = MagicMock()
            mock_llm.generate_summary.return_value = "No clinical notes available"
            mock_provider.return_value = mock_llm

            response = client.get(f"/api/v1/patients/{patient['id']}/summary")

            assert response.status_code == 200
            data = response.json()
            assert data["note_count"] == 0


class TestSummaryAsyncWorkflow:
    """Test asynchronous summary generation workflow."""

    def test_create_async_summary_job(self, seeded_database):
        """Test creating async summary job."""
        client = seeded_database["client"]
        patient = seeded_database["patients"][0]

        with patch("app.api.v1.summary.generate_summary_task") as mock_task:
            mock_result = MagicMock()
            mock_result.id = "test-job-id-123"
            mock_task.delay.return_value = mock_result

            response = client.post(
                f"/api/v1/patients/{patient.id}/summary/async?audience=clinician"
            )

            assert response.status_code == 202
            data = response.json()
            assert data["job_id"] == "test-job-id-123"
            assert data["status"] == "queued"
            assert "message" in data

    def test_get_pending_job_status(self, seeded_database):
        """Test getting status of pending job."""
        client = seeded_database["client"]
        patient = seeded_database["patients"][0]

        with patch("app.api.v1.summary.AsyncResult") as mock_async:
            mock_result = MagicMock()
            mock_result.status = "PENDING"
            mock_result.ready.return_value = False
            mock_async.return_value = mock_result

            response = client.get(
                f"/api/v1/patients/{patient.id}/summary/jobs/test-job-id"
            )

            assert response.status_code == 200
            data = response.json()
            assert data["status"] == "pending"
            assert data["result"] is None

    def test_get_processing_job_status(self, seeded_database):
        """Test getting status of processing job."""
        client = seeded_database["client"]
        patient = seeded_database["patients"][0]

        with patch("app.api.v1.summary.AsyncResult") as mock_async:
            mock_result = MagicMock()
            mock_result.status = "STARTED"
            mock_result.ready.return_value = False
            mock_async.return_value = mock_result

            response = client.get(
                f"/api/v1/patients/{patient.id}/summary/jobs/test-job-id"
            )

            assert response.status_code == 200
            data = response.json()
            assert data["status"] == "processing"

    def test_get_completed_job_status(self, seeded_database):
        """Test getting status of completed job."""
        client = seeded_database["client"]
        patient = seeded_database["patients"][0]

        expected_result = {
            "heading": {
                "name": "John Smith",
                "age": 45,
                "mrn": "MRN-00001"
            },
            "summary": "Complete summary text",
            "note_count": 2
        }

        with patch("app.api.v1.summary.AsyncResult") as mock_async:
            mock_result = MagicMock()
            mock_result.status = "SUCCESS"
            mock_result.ready.return_value = True
            mock_result.result = expected_result
            mock_async.return_value = mock_result

            response = client.get(
                f"/api/v1/patients/{patient.id}/summary/jobs/test-job-id"
            )

            assert response.status_code == 200
            data = response.json()
            assert data["status"] == "completed"
            assert data["result"] == expected_result

    def test_get_failed_job_status(self, seeded_database):
        """Test getting status of failed job."""
        client = seeded_database["client"]
        patient = seeded_database["patients"][0]

        with patch("app.api.v1.summary.AsyncResult") as mock_async:
            mock_result = MagicMock()
            mock_result.status = "FAILURE"
            mock_result.ready.return_value = True
            mock_result.result = {"error": "LLM provider unavailable"}
            mock_async.return_value = mock_result

            response = client.get(
                f"/api/v1/patients/{patient.id}/summary/jobs/test-job-id"
            )

            assert response.status_code == 200
            data = response.json()
            assert data["status"] == "failed"

    def test_async_job_for_nonexistent_patient(self, client):
        """Test creating async job for patient that doesn't exist."""
        response = client.post("/api/v1/patients/99999/summary/async")
        assert response.status_code == 404

    def test_async_summary_with_parameters(self, seeded_database):
        """Test async summary with custom parameters."""
        client = seeded_database["client"]
        patient = seeded_database["patients"][0]

        with patch("app.api.v1.summary.generate_summary_task") as mock_task:
            mock_result = MagicMock()
            mock_result.id = "job-with-params"
            mock_task.delay.return_value = mock_result

            response = client.post(
                f"/api/v1/patients/{patient.id}/summary/async"
                "?audience=family&max_length=300"
            )

            assert response.status_code == 202
            mock_task.delay.assert_called_once_with(
                patient.id, "family", 300
            )


class TestSummaryParameterValidation:
    """Test summary parameter validation."""

    def test_max_length_minimum(self, seeded_database):
        """Test max_length minimum constraint."""
        client = seeded_database["client"]
        patient = seeded_database["patients"][0]

        response = client.get(
            f"/api/v1/patients/{patient.id}/summary?max_length=50"
        )
        assert response.status_code == 422

    def test_max_length_maximum(self, seeded_database):
        """Test max_length maximum constraint."""
        client = seeded_database["client"]
        patient = seeded_database["patients"][0]

        response = client.get(
            f"/api/v1/patients/{patient.id}/summary?max_length=3000"
        )
        assert response.status_code == 422

    def test_valid_max_length_range(self, seeded_database):
        """Test valid max_length values."""
        client = seeded_database["client"]
        patient = seeded_database["patients"][0]

        with patch("app.services.summary_service.get_llm_provider") as mock_provider:
            mock_llm = MagicMock()
            mock_llm.generate_summary.return_value = "Summary"
            mock_provider.return_value = mock_llm

            # Test minimum valid
            response = client.get(
                f"/api/v1/patients/{patient.id}/summary?max_length=100"
            )
            assert response.status_code == 200

            # Test maximum valid
            response = client.get(
                f"/api/v1/patients/{patient.id}/summary?max_length=2000"
            )
            assert response.status_code == 200


class TestSummaryEndToEnd:
    """End-to-end summary workflow tests."""

    def test_complete_patient_journey_with_summary(self, client):
        """Test complete workflow: create patient, add notes, generate summary."""
        # Step 1: Create patient
        patient = client.post("/api/v1/patients", json={
            "name": "Complete Journey Patient",
            "date_of_birth": "1978-04-12"
        }).json()

        # Step 2: Add initial note
        client.post(f"/api/v1/patients/{patient['id']}/notes", json={
            "content": """S: Patient presents with acute symptoms
O: Vitals stable, exam findings noted
A: Initial diagnosis established
P: Begin treatment protocol""",
            "note_timestamp": "2024-01-10T09:00:00Z"
        })

        # Step 3: Add follow-up note
        client.post(f"/api/v1/patients/{patient['id']}/notes", json={
            "content": """S: Symptoms improving
O: Improved clinical findings
A: Responding to treatment
P: Continue current management""",
            "note_timestamp": "2024-01-17T09:00:00Z"
        })

        # Step 4: Generate summary
        with patch("app.services.summary_service.get_llm_provider") as mock_provider:
            mock_llm = MagicMock()
            mock_llm.generate_summary.return_value = (
                "Patient presented with acute symptoms and has shown "
                "improvement with treatment. Continue current management."
            )
            mock_provider.return_value = mock_llm

            summary_response = client.get(
                f"/api/v1/patients/{patient['id']}/summary"
            )

            assert summary_response.status_code == 200
            summary = summary_response.json()
            assert summary["heading"]["name"] == "Complete Journey Patient"
            assert summary["note_count"] == 2
            assert len(summary["summary"]) > 0

    def test_summary_updates_with_new_notes(self, client):
        """Test that summary reflects newly added notes."""
        # Create patient with one note
        patient = client.post("/api/v1/patients", json={
            "name": "Dynamic Summary Patient",
            "date_of_birth": "1985-06-20"
        }).json()

        client.post(f"/api/v1/patients/{patient['id']}/notes", json={
            "content": "Initial consultation note",
            "note_timestamp": "2024-01-10T09:00:00Z"
        })

        # Generate first summary
        with patch("app.services.summary_service.get_llm_provider") as mock_provider:
            mock_llm = MagicMock()
            mock_llm.generate_summary.return_value = "Summary with 1 note"
            mock_provider.return_value = mock_llm

            summary1 = client.get(f"/api/v1/patients/{patient['id']}/summary").json()
            assert summary1["note_count"] == 1

        # Add another note
        client.post(f"/api/v1/patients/{patient['id']}/notes", json={
            "content": "Follow-up consultation note",
            "note_timestamp": "2024-01-17T09:00:00Z"
        })

        # Generate second summary
        with patch("app.services.summary_service.get_llm_provider") as mock_provider:
            mock_llm = MagicMock()
            mock_llm.generate_summary.return_value = "Summary with 2 notes"
            mock_provider.return_value = mock_llm

            summary2 = client.get(f"/api/v1/patients/{patient['id']}/summary").json()
            assert summary2["note_count"] == 2

    def test_summary_after_note_deletion(self, client):
        """Test that summary updates after note deletion."""
        # Create patient with notes
        patient = client.post("/api/v1/patients", json={
            "name": "Note Deletion Patient",
            "date_of_birth": "1990-01-01"
        }).json()

        note1 = client.post(f"/api/v1/patients/{patient['id']}/notes", json={
            "content": "First note",
            "note_timestamp": "2024-01-10T09:00:00Z"
        }).json()

        client.post(f"/api/v1/patients/{patient['id']}/notes", json={
            "content": "Second note",
            "note_timestamp": "2024-01-11T09:00:00Z"
        })

        # Delete first note
        client.delete(f"/api/v1/patients/{patient['id']}/notes/{note1['id']}")

        # Generate summary
        with patch("app.services.summary_service.get_llm_provider") as mock_provider:
            mock_llm = MagicMock()
            mock_llm.generate_summary.return_value = "Summary after deletion"
            mock_provider.return_value = mock_llm

            summary = client.get(f"/api/v1/patients/{patient['id']}/summary").json()
            assert summary["note_count"] == 1
